language: php

php:
  - 7.2

script:
  - chmod +x build-libs/phing-2.4.9/bin/phing
  - bash ./build.sh || travis_terminate 1;

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "g8flVuvxcHsZMOQzcM0go1VSk4InbVGIQDVfqbLpH097nOdkCheXZjZIjBFdTMmUbvXny1Mph2FScEpqeSR2zBw35pkgup3QTT8oh25pVYQHlqjUPu1kYHB0M33ZCdEGyPCJnDPW+IxHSoL8a9Jx79wEgHMvjVzQrqaf2arfSJQ="
  file_glob: true
  file: deliverables/artifacts/*
  on:
    tags: true
