#
# This build script is provided by: https://github.com/svparijs/TravisCi.Example
# Author: Sebastiaan van Parijs
#
# For any issues of feedback report it at Github
#
# The TYPO3 project - inspiring people to share!
#

# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:

  # aliased to a recent 5.3.x version
  - 5.3
  # aliased to a recent 5.4.x version
  - 5.4

# Setting up pre-requirements
before_script:
  - ./build-libs/travis-phing.sh

script:
  - ./build.sh