language: php

php:
- 7.2

script:
- chmod +x build-libs/phing-2.4.9/bin/phing
- bash ./build.sh || travis_terminate 1;

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "zH31PiYmCS03x20rK5Gp6kypYEeLzKyuZjlqIeW8y+U99xKm4fDJhGtTbeOtONh0dGgDB7xnKY59az4C0n3qRgWr2TAtfU0qE3dip+hnQdCnEORDXkUi5DZbgO/a1TfJkppAvhM3OxgLwIdGZZc7mbFryYM1DTBatypBT5ArpTo="
  file_glob: true
  file: deliverables/artifacts/*
  on:
    tags: true
