language: php
php:
- 7.2
- 5.4
script:
- chmod +x build-libs/phing-2.4.9/bin/phing
- chmod +x ./build.sh
- "./build.sh"
branches:
  only:
  - master
deploy:
  provider: releases
  api_key:
    secure: DcY686RvBLGCljgeXw5phlTUFCQUlVNz+8H23OuDJGxVXL0VduVKD4eFBDTNrBn2uwbf4uBt6Me+nGJHZ/CJ2IsIq3nxul6W3T8s5ueHNViG54gdSjLf/+PPaH1XfIvXdY4rH7dLnGwYqRHCz5Hi03fnp14T7sbtF8hGXf4Ar4E=
  file: /home/travis/build/aparraga/phal/deliverables/artifacts/*
  on:
    repo: aparraga/phal
