language: php

php:
  - 7.2

script:
  - chmod +x build-libs/phing-2.4.9/bin/phing
  - bash ./build.sh || travis_terminate 1;

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "gE1uhKd/EWrAtDjuSEySF3yuofsW2hqORT2dKZmwdTAOXwJscMd55Sx+bO+fYIAd7nyj8sIB6qNAN1AoQVXM4dj9BkWMhqZY9v3YI/BTKBy+VNylxgYv3FQCo9h5cifA/xMOimNyJAvnFjCTzGsHH+J/jXOn8u3Z+AjXaI362pQ="
  file_glob: true
  file: deliverables/artifacts/*
  on:
    tags: true
