language: php

php:
  - 7.2

script:
  - chmod +x build-libs/phing-2.4.9/bin/phing
  - bash ./build.sh || travis_terminate 1;

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "hPU9TwySYJvQpVu8a6tQrATWPHeysQSVWU1rP2WHcPn/gVqYJzBwlrCaNPmD7ebZqY38DFPghFiUyCdI2X3Sw1e4xjnnhIoe05JNQxbSJnunpNvCJnl/cH2ZQc/yM3gwW4cEt7E6+ZkoSeR91RujPnnw/S2nzDAxaD8TC0IgWCU="
  file_glob: true
  file: deliverables/artifacts/*
  on:
    tags: true
