language: php

php:
- 7.2

script:
- chmod +x build-libs/phing-2.4.9/bin/phing
- bash ./build.sh || travis_terminate 1;

deploy:
  provider: releases
  skip_cleanup: true
  secure: R/0UPKf4+kDK1CjwEAb+TKH8U7xPgBnaVa57Xo8L70SFzRIleWFwwZD/rn/pX9h4M+ultk0v2Cbn8c4kU6M1sdV10KuFKu1AGIsQxXGZ9qGVJaWTcfQeUeyaA4YxpT54AftebWZ2IoLviU/7kDsvjaBNdIxo/ToVwQilVSNKPAc=
  file_glob: true
  file: deliverables/artifacts/*
  on:
    tags: true
