language: php

php:
  - 7.2

script:
  - chmod +x build-libs/phing-2.4.9/bin/phing
  - bash ./build.sh || travis_terminate 1;

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "U3fcwfDkZD+f8Y9Bc35cVV2aXdbhlFs6Lkd1Sau7xCC9LUCZtOIXMc2Ib1ugb+089ziF3lzKgqpUAxSe5rSIYGCeCtGlvFsGh6EO2+ISnO7Os0ROtMpUSxare7Ru22n9p7xfSXMXTDplc9rXVmiufJxznKpj2mMQhdsMIRMV0dE="
  file_glob: true
  file: deliverables/artifacts/*
  on:
    tags: true
