name: build

on:
  push:
    tags:
      - '0.**'
      - '1.**'

env:
  PHP_VERSION: 7.2

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
          ini-values: 'phar.readonly=Off'

      - name: Build deliverables
        run: |
          export RELEASE_VERSION=${GITHUB_REF##*/}          
          chmod +x ./build-libs/phing-2.4.9/bin/phing
          bash ./build.sh

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "deliverables/artifacts/*"
